function gui = createResponseGUI()

    gui.response = [];
    gui.ready = false;

    gui.fig = figure( ...
        'Position',[100 100 500 320], ...
        'MenuBar','none', ...
        'ToolBar','none', ...
        'Name','Participant Response', ...
        'NumberTitle','off', ...
        'Resize','off', ...
        'Color','white', ...
        'WindowStyle','modal', ...
        'KeyPressFcn', @keyPressCallback, ...
        'CloseRequestFcn', @closeExperiment);
    
    movegui(gui.fig, 'center');

    gui.questionText = uicontrol( ...
        'Style','text', ...
        'String','PLACEHOLDER', ...
        'Position',[50 140 400 120], ...
        'FontSize',14, ...
        'BackgroundColor','white');

    gui.yesButton = uicontrol( ...
        'Style','pushbutton', ...
        'String','Yes (1)', ...
        'FontSize',14, ...
        'Position',[60 40 160 90], ...
        'Callback', @(src,event)buttonCallback(1));
    
    gui.noButton = uicontrol( ...
        'Style','pushbutton', ...
        'String','No (0)', ...
        'FontSize',14, ...
        'Position',[280 40 160 90], ...
        'Callback', @(src,event)buttonCallback(0));

    gui.trialText = uicontrol( ...
        'Style','text', ...
        'String','Trial 0', ...
        'Position',[140 290 220 20], ...
        'FontSize',12, ...
        'BackgroundColor','white');

    setappdata(gui.fig,'response',[]);

    function closeExperiment(~, ~)
        if isvalid(gui.fig)
            delete(gui.fig);
        end
        error('Experiment terminated by participant.');
    end

    function buttonCallback(val)
        mode = getappdata(gui.fig,'mode');
    
        switch mode
            case 'question'
                setappdata(gui.fig,'response',val);
    
            case {'start','end','break'}
                setappdata(gui.fig,'response','CONTINUE');
        end
    end
    
    function keyPressCallback(~, event)
        mode = getappdata(gui.fig,'mode');
    
        % Only accept literal 0 or 1 characters
        ch = event.Character;
    
        if ~(strcmp(ch,'0') || strcmp(ch,'1'))
            return;   % ignore everything else, including volume keys
        end
    
        switch mode
            case 'question'
                if strcmp(ch,'1')
                    setappdata(gui.fig,'response',1);
                elseif strcmp(ch,'0')
                    setappdata(gui.fig,'response',0);
                end
    
            case {'start','end', 'break'}
                setappdata(gui.fig,'response','CONTINUE');
            otherwise
                return;
        end
    end
end