function gui = createResponseGUI()

    gui.response = [];
    gui.ready = false;

    gui.fig = figure( ...
        'Position',[100 100 500 250], ...
        'MenuBar','none', ...
        'ToolBar','none', ...
        'Name','Participant Response', ...
        'NumberTitle','off', ...
        'Resize','off', ...
        'Color','white', ...
        'WindowStyle','modal', ...
        'KeyPressFcn', @keyPressCallback, ...
        'CloseRequestFcn', @closeExperiment);
    
    movegui(gui.fig, 'center');

    gui.questionText = uicontrol( ...
        'Style','text', ...
        'String','Did the pause sound natural?', ...
        'Position',[50 160 400 50], ...
        'FontSize',14, ...
        'BackgroundColor','white');

    gui.yesButton = uicontrol( ...
        'Style','pushbutton', ...
        'String','Yes (1)', ...
        'FontSize',14, ...
        'Position',[60 40 160 90], ...
        'Callback', @(src,event)buttonCallback(1));
    
    gui.noButton = uicontrol( ...
        'Style','pushbutton', ...
        'String','No (0)', ...
        'FontSize',14, ...
        'Position',[280 40 160 90], ...
        'Callback', @(src,event)buttonCallback(0));

    gui.trialText = uicontrol( ...
        'Style','text', ...
        'String','Trial 0', ...
        'Position',[180 220 140 20], ...
        'FontSize',12, ...
        'BackgroundColor','white');

    setappdata(gui.fig,'response',[]);

    function closeExperiment(~, ~)
        if isvalid(gui.fig)
            delete(gui.fig);
        end
        error('Experiment terminated by participant.');
    end

    function buttonCallback(val)
        mode = getappdata(gui.fig,'mode');
    
        switch mode
            case 'question'
                setappdata(gui.fig,'response',val);
    
            case {'start','end'}
                setappdata(gui.fig,'response','CONTINUE');
        end
    end
    
    function keyPressCallback(~, event)
        mode = getappdata(gui.fig,'mode');
    
        switch mode
            case 'question'
                switch event.Key
                    case {'1','numpad1'}
                        setappdata(gui.fig,'response',1);
                    case {'0','numpad0'}
                        setappdata(gui.fig,'response',0);
                end
    
            case {'start','end'}
                % any key continues
                setappdata(gui.fig,'response','CONTINUE');
        end
    end
end